export const shopActionTypes = {
    UPDATE_COLLECTIONS:'UPDATE_COLLECTIONS',
    START_FETCHING_COLLECTIONS: 'START_FETCHING_COLLECTIONS',
    SUCCESS_FETCHING_COLLECTIONS: 'SUCCESS_FETCHING_COLLECTIONS',
    FAILURE_FETCHING_COLLECTIONS: 'FAILURE_FETCHING_COLLECTIONS'
}